services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: jobtracker-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./Frontend
    container_name: jobtracker-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
